name: neural_gate
description: "Neural Interface Dashboard for ESP32"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  web_socket_channel: ^2.4.0
  provider: ^6.1.1
  url_launcher: ^6.2.2
  flutter_blue_plus: ^1.31.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true